m4_include([m4/ax_cflags_warn_all.m4])
m4_include([m4/ax_compiler_vendor.m4])
m4_include([m4/ax_cflags_gcc_option.m4])
m4_include([m4/ax_cflags_sun_option.m4])
m4_include([m4/ax_cflags_aix_option.m4])
